# Generated by Django 4.2.6 on 2023-10-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100)),
                ('cabinet', models.IntegerField()),
                ('department', models.IntegerField()),
                ('user_name', models.CharField(max_length=30)),
                ('pc_name', models.CharField(max_length=30)),
                ('ip', models.GenericIPAddressField()),
            ],
        ),
    ]
